[
  {
    "test": "Admin Authentication",
    "success": false,
    "details": "Exception: HTTPConnectionPool(host='localhost', port=8001): Max retries exceeded with url: /api/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xfd4712c3ad10>: Failed to establish a new connection: [Errno 111] Connection refused'))",
    "timestamp": "2025-09-10T16:13:14.354992",
    "data": null
  }
]